### ISSUE TITLE
/16 networks

### ISSUE THREAD

**Issue by reesericci** [techno-tim/techno-broadlink#21]
Currently, the discovery only works on /24 networks, so it doesn't pick up my broadlink.

**Comment by timothystewart6** [comment]
It should work on any network but you'll need to be sure those networks accepts broadcasts

**Comment by reesericci** [comment]
Is there a setting in UniFi?

**Comment by timothystewart6** [comment]
I think it's `mDNS` in UniFi.

**Comment by timothystewart6** [comment]
Closing this since this is a networking issue and not related to the service.  You'll need to make sure your network can send broadcasts across subnets.
