### ISSUE TITLE
docker run issue

### ISSUE THREAD

**Issue by dalton5** [techno-tim/techno-broadlink#45]
Hi,

I run this command:

`docker run -e HOST_IP=192.168.0.37 -p 10981:10981 -v /opt/broadlink/config:/app/config --network host timothystewart6/techno-broadlink:latest`

I have the warning:  
    docker : WARNING: Published ports are discarded when using host network mode
    Au caractère Ligne:1 : 1
    + docker run -e HOST_IP=192.168.0.37 -p 10981:10981 -v /broadlink/confi ...
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (WARNING: Publis...st network mode:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

It's installed correctly in docker desktop but I can't access the webpage.

![image](https://user-images.githubusercontent.com/8339768/174440040-0ee11e80-1f30-40f9-a656-b67fffa6f5c1.png)

But I still have this issue:

![image](https://user-images.githubusercontent.com/8339768/174440058-04f12872-1501-4824-b3b9-cf1238ccabc7.png)

What is wrong?

Thanks,

**Comment by dalton5** [comment]
ok some news. It works when I remove --network host. is it mandatory?

**Comment by timothystewart6** [comment]
It is https://github.com/techno-tim/techno-broadlink#usage  :)

**Comment by dalton5** [comment]
Sorry but I am lost. Which variable do I have to replace?

IP and </path/to/config>? correct?

docker run \
  -e HOST_IP=your.docker.host.ip \
  -p 10981:10981 \
  -v </path/to/config>:/app/config \
  --network host \
  timothystewart6/techno-broadlink

**Comment by timothystewart6** [comment]
Hi!  If you're confused on how to set this up, see my video on it along with the documentation that's linked there!

https://www.youtube.com/watch?v=4MJW29mR-Xc

**Comment by jpasantos** [comment]
Setting up ports with network host doesn't work. So to use with network=host just remove the port config

Also network host doesn't work with Windows WSL so make sure you're using linux
