### ISSUE TITLE
Missing folder required within Dockerfile

### ISSUE THREAD

**Issue by 22simc22** [techno-tim/techno-broadlink#49]
In Dockerfile there is this command: `COPY frontend/build .` but _build_ folder is missing in GitHub repo.

**Comment by timothystewart6** [comment]
It gets built during CI
https://github.com/techno-tim/techno-broadlink/blob/master/.github/workflows/main.yml#L25

**Comment by jpasantos** [comment]
go to frontend and run
yarn install
and then
yarn build

If you have node > 16 replace line 27 and 28 of package.json with
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider build",
