### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by tophee** [techno-tim/techno-broadlink#8]
Really great project! Was so easy to set up!

But now I want to use the API but I'm not sure how to do it. Based on the postman file I'm trying to understand what a curl request might look like, but I'm completely new to using APIs at that level and I'v never user postman either, so I'm kinda stuck. Could you explain the basic structure of how the API is addressed and perhaps provide an example? 

Do I understand correctly that the API cannot be used by simply calling a URL in the browser?

In case it matters, what I'm actually trying to do is adress your app via OpenHAB.

**Comment by timothystewart6** [comment]
Hey!  Thank you!  I think the easiest way, if you want to use `curl` commands, is to install postman, import the collection, then convert them to `curl` commands from there.

It's easy

* install postman
* download the `postman/techno-broadlink.postman_collection.json` file
* import it
* open the collection
* change the IP from `localhost` to your server ip running this container
* execute the command with send
* if you want a `curl` command, choose the code icon on the right `</>` and it will show you the command
* run that command from a terminal

**Comment by timothystewart6** [comment]
closing this but open to discuss more
